# Generated by Django 4.2.4 on 2023-10-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_rename_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=5)),
                ('quantity', models.IntegerField(max_length=99)),
            ],
        ),
    ]
