# Generated by Django 4.2.4 on 2023-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
