# Generated by Django 4.2.4 on 2023-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(max_length=30)),
                ('product_id', models.IntegerField(max_length=5)),
                ('quantity', models.IntegerField(max_length=99)),
            ],
        ),
    ]
