# Generated by Django 4.2.4 on 2023-10-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
