# Generated by Django 4.2.4 on 2023-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_cart_price_cart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
