# Generated by Django 4.2.4 on 2023-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
