# Generated by Django 4.2.4 on 2023-10-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(max_length=16),
        ),
    ]
