# Generated by Django 4.2.4 on 2023-10-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_alter_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
